server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eMart?serverTimezone=UTC
    username: mmall
    password: mmall
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: zuul-service

eureka: 
  instance: 
    hostname: localhost
    lease-renewal-interval-in-seconds: 25
    lease-expiration-duration-in-seconds: 30
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8081/eureka
      
zuul:
#   ignored-services:
#    "*"
   routes: 
      user: 
        path: /user/** 
        serviceId: user-service
      items: 
        path: /items/** 
        serviceId: items-service
      order: 
        path: /order/** 
        serviceId: order-service
      fileinfo:
        path: /fileinfo/** 
        serviceId: fileinfo-service
        