server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eMart?serverTimezone=UTC
    username: mmall
    password: mmall
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: order`

eureka: 
  instance: 
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8081/eureka
      