server:
  port: 8085

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/eMart?serverTimezone=UTC
#    username: mmall
#    password: mmall
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#      dialect: org.hibernate.dialect.MySQL5Dialect
  main: 
    allow-bean-definition-overriding: true
  application:
    name: feign-service

eureka: 
  instance: 
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8081/eureka
      
ribbon: 
   eureka: 
      enabled: true
      